---
gancio_url: https://deine-instanz.gancio.org
username: admin@example.org
password_file: /run/secrets/gancio_password
state_file: /opt/ical2gancio/state.json

ical_urls:
  - url: https://kreativfabrik-wiesbaden.de/veranstaltungen/?ical=1
    default_place_name: Kreativfabrik Wiesbaden
    default_place_address: Murnaustraße 1, 65189 Wiesbaden
    additional_tags:
      - kreativfabrik

  - url: https://andere-location.org/events/?ical=1
    default_place_name: Andere Location
    default_place_address: Musterstraße 42, 12345 Musterstadt
    additional_tags:
      - andere-location
      - musterstadt
